name: Release

on:
  release:
    types: [created]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Find JAR file
        id: find_jar
        run: |
          JAR_PATH=$(ls ./build/libs/mojang2tiny-*.jar | head -n 1)
          echo "jar_path=$JAR_PATH" >> $GITHUB_OUTPUT

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.find_jar.outputs.jar_path }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
